### ISSUE TITLE
Error after Install

### ISSUE THREAD

**Issue by jenswittmann** [BobRay/UpgradeMODX#1]
Hello Bob,
thanks for the work on a plugin like this. Its really important for MODX!

I install it now, but i get an error:
`Fatal error: Can't use method return value in write context in /core/cache/includes/elements/modsnippet/73.include.cache.php on line 168`

I will look for a solution, but first i want to push it to you, maybe you know it first.

Cheers
Jens

**Comment by jenswittmann** [comment]
Ah, i don't use PHP 5.6! Maybe its important for older Version. Now it works.

**Comment by BobRay** [comment]
Hi Jens,

Can you give me line 178 if this cache file:

/includes/elements/modsnippet/73.include.cache.php


I'm having trouble locating the problem line. I'd like to fix it for people
with other versions of PHP.

Cheers,

Bob

**Comment by jenswittmann** [comment]
For sure:

167 /* Update Properties if there are no cURL errors */
168 if (empty($this->getErrors())) {
169            $snippet = $this->modx->getObject('modSnippet', array('name' => 'UpgradeMODXWidget'));

**Comment by BobRay** [comment]
Thanks! I was able to fix it (I hope). I've released a new version.

Cheers,

Bob

**Comment by BobRay** [comment]
Hi Jens,

I've released an rc version that should solve that problem and others.  Let
me know if you have any problems with it.


Thanks for the feedback on the earlier version.

Cheers,

Bob
