### ISSUE TITLE
Upgrade MODX Revolution Advanced

### ISSUE THREAD

**Issue by gravino81** [BobRay/UpgradeMODX#10]
Hello Bob,
It does not work with the Advanced version?

**Comment by BobRay** [comment]
It does for me. :)

If you're having trouble, can you be more specific about what's happening?

**Comment by gravino81** [comment]
I tried on different servers, at first server disconnected me from the manager and does not allow me do anything else, on another I started with the setup but does not see my previous installation and the only one that allows me to do is to do a new installation. Tonight I will more test!

**Comment by labr1005** [comment]
Works for me without any problems.
But it changes the system setting "settings_distro" from "advanced" to "traditional".
Is this the only side effect?

**Comment by BobRay** [comment]
I'm pretty sure that's the only side effect. It downloads the traditional distro because it's more likely to work. I don't think there's a way to preserve that System Setting, since setup is doing it, and by that time, UGM is out of the picture.
