### ISSUE TITLE
Upgrade offers downgrade versions

### ISSUE THREAD

**Issue by wuuti** [BobRay/UpgradeMODX#14]
When I choose upgrade I am offered the following versions for my 2.4.3 (plOnly was configured to no):

- MODX Revolution 2.5.0-rc1
- MODX Revolution 2.4.3-pl
- MODX Revolution 2.4.2-pl
- MODX Revolution 2.4.1-pl
- MODX Revolution 2.4.0-rc1

As downgrade is not tested (and imho is totally useless and not really provided by modx), the script should never give the option to downgrade an installation (by default).

**Comment by BobRay** [comment]
I have not tested it extensively, but it's my understanding that it's common for people to use UGM to downgrade MODX. I can't think of any reason it would cause a problem, but maybe I'm missing something.

**Comment by inreti** [comment]
You may be better informed about the usage here. But I cannot think of a good reason to downgrade an installation. At least this offers a way to re-introduce security issues, and that should not be supported, should it?

**Comment by sebastian-marinescu** [comment]
I can think of a good reason to downgrade: make the site work again, if a new version chopped everything to disaster-place. Isn't that good enough?
But maybe this behavior could be a setting, what do you think?

**Comment by BobRay** [comment]
I will leave it as an option, though people can use it at their own risk. No one is forced to downgrade with the current settings. BTW, people often want to "Upgrade" to the version they already have when they have trouble and the cause might be a corrupted file in the process.
