### ISSUE TITLE
Delete leftover on unsucessfull download

### ISSUE THREAD

**Issue by Jako** [BobRay/UpgradeMODX#18]
If 'cUrl download of modx.zip failed malformed' occurs, the upgrade.php and the modx.zip files should be deleted after clicking on back to manager, since they are not needed.

They should not be deleted directly, for debugging reasons.

**Comment by BobRay** [comment]
Jako, I was planning to do this, but then a couple of users reported success in running the upgrade.php file after manually downloading the modx.zip file (leaving it there shows them where it should go).

Since both files are harmless, I think I'll leave it alone.

**Comment by Jako** [comment]
Then please warn the users, that they have to be deleted. I don't think that they are that harmless. They could at least be detected easily and show that this is a MODX installation. 

If they are located in a random folder, that would be not the case. I am not sure, wether a random folder would be possible.

**Comment by BobRay** [comment]
Done! I updated the Security section of the docs. Thanks for the tip.
