### ISSUE TITLE
Don't create the UpgradeMODX resource by default

### ISSUE THREAD

**Issue by Jako** [BobRay/UpgradeMODX#21]
Prepare a setupoptions resolver for this.

**Comment by sebastian-marinescu** [comment]
+1

**Comment by digitalpenguin** [comment]
+1

**Comment by sebastian-marinescu** [comment]
+1 again, because I had to delete the second generated resource again :)

**Comment by BobRay** [comment]
If the alias of the resource is upgrade-modx, UGM shouldn't touch it or create another.
