### ISSUE TITLE
Problem with 2.5.0

### ISSUE THREAD

**Issue by natedin** [BobRay/UpgradeMODX#22]
Hey,

I'm trying to upgrade a site from 2.3.5 to the latest version, when I select 2.5.0 it loads for a few seconds and then goes to a page just saying "Back to Manager".

I've upgraded to 2.4.4, and that worked fine (it does the same trying to upgrade from 2.4.4)

Thanks

**Comment by sebastian-marinescu** [comment]
Hi, is it still the same with an upgrade to 2.5.1? 
If so, what errors do you get? Please check your server-logs and especially the PHP Error-Log.

**Comment by natedin** [comment]
Sorry missed this reply!

I ended up manually upgrading the site to 2.5.x and then with UpgradeMODX to 2.5.2 (which worked fine) however on another site with https I'm getting empty modx package when trying to upgrade.
