### ISSUE TITLE
Rate Limiting on Shared Hosts

### ISSUE THREAD

**Issue by neoneddy** [BobRay/UpgradeMODX#23]
I'm not sure what the work around might be.  I'm fine with even feeding the widget a URL to the upgrade zip in the case of a failure.

![image](https://cloud.githubusercontent.com/assets/819083/16992903/ca20ad84-4e66-11e6-8be4-3f24549c2268.png)

**Comment by sebastian-marinescu** [comment]
Hm... have you tried entering your Github Username/Api-Key inside the properties of the UpgradeMODX-Snippet? Maybe then GH will still give you Api-Access?

**Comment by ukwiz** [comment]
Hijacking this, but I have created a personal access token in github (but not sure what to authorise, so included everything) but still get the above error

**Comment by BobRay** [comment]
Sorry for the late reply. My notifications from GitHub were broken.

The only thing I can think of is that your github credentials are not correct.

**Comment by neoneddy** [comment]
I wasn't using any creds. Yes I think that might fix it. I also found hitting the upgrade resource directly works.
