### ISSUE TITLE
open_basedir redirect issue

### ISSUE THREAD

**Issue by Jako** [BobRay/UpgradeMODX#30]
The new folder structure on the MODX site causes some issues on `open_basedir` restricted hosts.

The currrent version of the upgrade.php script of UpgradeMODX notices only one redirect. But 
`http://modx.com/download/direct/modx-2.5.2-pl.zip` redirects to `https://modx.com/download/direct/modx-2.5.2-pl.zip` that redirects to `https://modx.com/download/direct?id=modx-2.5.2-pl.zip` that redirects to 
Amazon AWS. So please create the download url with the last string of this chain: `https://modx.com/download/direct?id=modx-2.5.2-pl.zip` and it will work until you have a real recursive redirect method inside of UpgradeMODX.

Example for a recursive method: https://gist.github.com/Jako/c9ea82324c62c90c15ade95254ac57e1

**Comment by Jako** [comment]
Quick fix in #31

**Comment by BobRay** [comment]
Just merged your PR. Jason is working on an API for UGM to use, so that may mitigate the redirect issue.
