### ISSUE TITLE
(GitHub -- curl) API rate limit exceeded

### ISSUE THREAD

**Issue by matdave** [BobRay/UpgradeMODX#36]
Not sure how to go about fixing this, but just noticed my sites started getting this error `(GitHub -- curl) API rate limit exceeded for X.X.X.X`. 
![image](https://user-images.githubusercontent.com/2213127/34846220-122a5bd2-f6dd-11e7-8c91-fd3e04d6efa3.png)

**Comment by BobRay** [comment]
Check here: [https://bobsguides.com/upgrade-modx-package.html](https://bobsguides.com/upgrade-modx-package.htmll)

See the section titled:

GitHub API Rate Limit Exceeded

**Comment by matdave** [comment]
Thanks, I added the system settings for github_user and github_token and it's working.
