### ISSUE TITLE
Error: Could not get version list from GitHub. error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by Plushkin** [BobRay/UpgradeMODX#39]
Upgrade MODX

Error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Could not get version list from GitHub

**Comment by BobRay** [comment]
Are you behind a proxy server?

**Comment by Plushkin** [comment]
No

**Comment by Plushkin** [comment]
MODX Revolution 2.3.5-pl (traditional)
Кодовое имя версии:
Revolution
phpinfo():
Просмотреть
Серверное время:
04:38:23 PM
Местное время:
04:38:23 PM
Смещение серверного времени:
0
Версия ExtJS:
3.4.1
Версия Smarty:
3.0.4
Версия PHPMailer:
5.2.8
Версия MagpieRSS:
0.72
Тип базы данных:
mysql
Версия базы данных:
4.1.25-log
Кодировка базы данных:
utf8
Имя базы данных:
wwwsaromatru_aromat
Сервер базы данных:
mysql.saromat.mass.hc.ru
Префикс таблицы:
modx_
MySQL Support:
enabled
Active Persistent Links:
0
Active Links:
0
Client API version:
mysqlnd 5.0.8-dev - 20102224 - $Id: 65fe78e70ce53d27a6cd578597722950e490b0d0 $
Directive:
Local Value,Master Value
mysql.allow_local_infile:
On,On
mysql.allow_persistent:
Off,Off
mysql.connect_timeout:
-1,-1
mysql.default_host:
no value,no value
mysql.default_password:
no value,no value
mysql.default_port:
no value,no value
mysql.default_socket:
no value,no value
mysql.default_user:
no value,no value
mysql.max_links:
Unlimited,Unlimited
mysql.max_persistent:
Unlimited,Unlimited
mysql.trace_mode:
Off,Off
PDO support:
enabled
PDO drivers:
sqlite, mysql, pgsql
PDO Driver for MySQL:
enabled
Client API version:
mysqlnd 5.0.8-dev - 20102224 - $Id: 65fe78e70ce53d27a6cd578597722950e490b0d0 $
Directive:
Local Value,Master Value
pdo_mysql.default_socket:
/tmp/mysql.sock,/tmp/mysql.sock
Zip:
enabled
Extension Version:
$Id$
Zip version:
1.9.1
Libzip version:
0.9.0

**Comment by BobRay** [comment]
I assume you're using Version 1.5.1 of UGM. If you've made several upgrades, you may have hit the GitHub rate limit. It could also be a timeout. You may need to create a github account and set the &github_username and &github_token properties. You can also try messing with the &githubTimeout property, the &attempts property, and the &forceFopen property.

**Comment by terrybarth** [comment]
I'm getting this error on one the dashboard on one of my sites. I'm working with server admin to resolve but I could use some help to help him.

Modx 2.6.1
PHP Version: 5.3.10-1ubuntu3.26
cURL Information | 7.22.0
SSL Version | OpenSSL/1.0.1

I've shared the forum posts about this where updating cURL and SSL were suggested as potential solutions to this problem. He's updated the system packets for both, but I'm stilling getting this error.

Since then, I've uninstalled, removed and reinstalled the updater, cleared cache, still no joy.

Any other ideas, I don't know how to help this guy. He a really sharp buy, but doesn't know Modx and I don't know much about server admin.

**Comment by BobRay** [comment]
You could try setting the forceFopen property of the widget snippet.  You might be hitting the GitHub rate limit.  You can avoid it by getting a free account at GitHub and adding your GitHub credentials to UGM in the github_token and github_username properties.

Also, try deleting the core/cache/upgrademodx/versionlist file. It could be corrupted.

**Comment by BobRay** [comment]
What do you see if you put this in your browser's address bar: https://api.github.com/repos/modxcms/revolution/tags

**Comment by terrybarth** [comment]
Done.  No change.

**Comment by BobRay** [comment]
OK, UGM uses its own cert file to avoid people having to set a path to it.  

The file is:  core\components\upgrademodx\cacert.pem.

Two more things to try.  You'll have to turn ssl_verify_peer back on to get these to take effect and clear the cache files again: 

1. Rename that cacert.pem file (for backup) and replace it with a new cert file (from your host) with the exact same name.

If that doesn't work:

2. Change the path in line 751 of the UpgradeMODXScriptSource chunk to point to the hosts cert file.

`$certPath = MODX_CORE_PATH . 'components/upgrademodx/cacert.pem';`

to

`$certPath = full/path/to/hosts/cert/file';`

**Comment by BobRay** [comment]
Closing this with one last suggestion. Turn off the MODX dashboard News and Security feeds and move them below the UGM widget on your dashboard, then clear the cache manually. If that works, try turning the feeds back on.
