### ISSUE TITLE
Not checking for allow_url_fopen

### ISSUE THREAD

**Issue by joyceDesignbase** [BobRay/UpgradeMODX#4]
First of all thank you for your hard work on this addon!

It all installed fine, no errors. Then when i choose a version to upgrade to and hit the Upgrade! button I get a blank screen. 
After some searching it appears that on my clients server allow_url_fopen = off.
In upgrade.php I see a check for this on line , but shouldn't that be: ini_get('allow_url_fopen')?
As it is now it goes on trying to install but fails because can not open necessary folder.

Greetings

**Comment by BobRay** [comment]
Good catch. Can you give me the line number? I'm having trouble finding the spot you mean.

**Comment by joyceDesignbase** [comment]
Hello Bob,

it's in elements/chunks/upgrademodxsnippetscriptsource.chunk.php on line 46.


--
Met vriendelijke groet,
 
Joyce Arends
 
 
Designbase 
Webcentre

Wiersedreef 10
3433 ZX Nieuwegein

T  030 608 48 21
F  030-608 48 23
E  joyce@designbase.nl 
W www.designbase.nl

**Comment by BobRay** [comment]
LOL - what a stupid mistake.

Can you tell me what happens when you change it to:

} elseif (ini_get('allow_url_fopen')) {

I can't test it because I don't have access to a server with that off.

**Comment by joyceDesignbase** [comment]
Haha it happens to the best of us :)

When I change it to ini_get('allow_url_fopen') I get a blank screen with only the expected error message: 'Neither allow_url_fopen or cURL is enabled, cannot download the MODX archive'


--
Met vriendelijke groet,
 
Joyce Arends
 
 
Designbase 
Webcentre

Wiersedreef 10
3433 ZX Nieuwegein

T  030 608 48 21
F  030-608 48 23
E  joyce@designbase.nl 
W www.designbase.nl

**Comment by BobRay** [comment]
Thanks for checking that. Others have reported the blank screen. I hope
that's the only cause. ;)

Cheers,

Bob
