### ISSUE TITLE
Problem upgrading from MODX from 2.6.4 to 2.6.5

### ISSUE THREAD

**Issue by andytough** [BobRay/UpgradeMODX#43]
If your MODX version is 2.6.4 UpgradeMODX 1.5.5 reports that the latest version available is 2.6.4, when it should be 2.6.5.

It was able to trick it into performing an upgrade by...

Changing **System Settings** / **settings_version** from **2.6.4** to **2.6.3**

Changing line 5 of  **/core/docs/version.inc.php** from

`$v['minor_version']= '4'; // Current minor version.`
to
`v['minor_version']= '3'; // Current minor version.`

Not sure of what I did wise?!

**Comment by andytough** [comment]
Thank you Bob.

**Comment by BobRay** [comment]
You're welcome.  :) 
FYI, the new version (due out soon) sets the time to check at one day.
