### ISSUE TITLE
Possibility for automatic upgrade feature?

### ISSUE THREAD

**Issue by 5koder** [BobRay/UpgradeMODX#45]
After the recent hacks I was wondering if you could implement an automatic upgrade option when new versions becomes available?

Or even a notification system to send out an email to a user... Just an idea

**Comment by BobRay** [comment]
It's an interesting idea, but every time it happened, it would log off all users.  If you subscribe to the  MODX news feed, you'll get an email every time a new important upgrade is available. I got one for 2.6.5.

**Comment by BobRay** [comment]
I'm going to close this as "won't fix any time soon."
