### ISSUE TITLE
Install issue on MODX Revolution 2.1.3-pl (traditional)

### ISSUE THREAD

**Issue by tschwade** [BobRay/UpgradeMODX#48]
Bob, I installed the most recent UpgradeMODX successfully on revo 2.3.2 and succeded in upgrading to 2.6.5, but when I try to install the same package to revo 2.1.3, I receive the following install errors:

MODX Console Output
@date 2018-08-06 15:57:17
Attempting to install package with signature: upgrademodx-1.5.5-pl
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Could not load class: modDashboardWidget from mysql.moddashboardwidget.
Could not load vehicle!
Could not load class: modDashboardWidget from mysql.moddashboardwidget.
modDashboardWidget::load() is not a valid static method.
Could not load class: modDashboard from mysql.moddashboard.
modDashboard::load() is not a valid static method.
Could not find Widget  Upgrade MODX
Could not find dashboard with ID 1
Successfully installed package upgrademodx-1.5.5-pl

Seems like revo 2.1.3 does not support widgets. Do you see another way of running UpgradeModx on that revo version? I hoped to get it running, since I read in your docs "Upgrades very old versions of MODX Revolution (tested on 2.0.3)".
Thanks in advance, Thomas

**Comment by BobRay** [comment]
2.1 has no support for third-party dashboard widgets, so UGM can't be installed as a widget in that version. See if there's an UpgradeMODX resource. Viewing it might let you run UGM.

**Comment by tschwade** [comment]
Thanks, this seems to work as soon as I have upgraded to a more recent PHP version.

**Comment by BobRay** [comment]
I'm glad you got it sorted.
