### ISSUE TITLE
Problem with CURL

### ISSUE THREAD

**Issue by Boddlnagg** [BobRay/UpgradeMODX#5]
Since the latest release, curl is used on my server instead of fopen (looks like fopen was used before because of a wrong check). But now with curl the downloading fails. UpgradeMODX reports an unknown error, and I didn't check the error log in that specific case, but the following warning is reported regularly:

```
[2015-10-10 20:39:04] (ERROR @ /.../core/model/modx/processors/system/config_check.inc.php : 94) PHP warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set
```

So I guess the file download requires following a redirect, which is not allowed with the `open_basedir` restriction?

Since it worked before with fopen, this is rather frustrating.

**Comment by BobRay** [comment]
Sorry about the trouble. The code at line 100 of the UpgradeModxScriptsource chunk is supposed to handle that case and follow manually without setting CURLOPT_FOLLOWLOCATION. I don't know why that's not working (or why the download fails). One possibility is that ini_get() is reporting both safe_mode and open_basedir as false. Could you try this in a snippet to check that?

    $output = '';
    $output .= 'Safe Mode: ' . ini_get('safe_mode;) . '<br />';
    $output .= 'Open Basedir: ' . ini_get('open_basedir');
    return $output;

As a workaround, you can add this as line 51:

    $method = 'fopen';

That will force it to use fopen again.

**Comment by Boddlnagg** [comment]
I should add that the error that is reported after the version is selected is the following (sorry that I didn't mention that before): `Unknown error reading /temp directory`.

So it might not be related to CURLOPT_FOLLOWLOCATION after all. Unfortunately nothing is reported in the error  log.

Running your snippet reports that safe_mode is false, and open_basedir is a list of directories which includes my webroot as well as `/tmp` (in case that matters here ...)

By the way, thanks for your quick response! Apart from this issue, UpgradeMODX is working great with my site and makes upgrading a lot simpler and faster!

**Comment by Serifenlos** [comment]
I had exactly the same error. Your mentioned workaround helped me to run the routine without any trouble.
Thank you for UpgradeMODX.

**Comment by BobRay** [comment]
@Boddlnagg: Did you try my workaround, or setting the forcePclZip property of to yes?

**Comment by Boddlnagg** [comment]
I had already downgraded to the previous version of the extra and done the MODX update with that. Therefore I did not test the workaround (but I assume that it would work) or changing the forcePclZip property.

**Comment by Boddlnagg** [comment]
I can confirm that (after working around #6), forcing `$method = 'fopen';` worked as expected!

**Comment by BobRay** [comment]
Thanks for the feedback.  At present, cURL is required for checking for a new version and checking to see if it's available at MODX. I'll try to make those checks use fopen too in the next version if &forceFopen is on.
