### ISSUE TITLE
Empty temp folders being created during update check

### ISSUE THREAD

**Issue by travisbotello** [BobRay/UpgradeMODX#52]
Just upgraded to version 2.0.2 on MODx 2.6.5 advanced installation and UpgradeMODX starts to create `ugmtemp/unzipped` folders inside `public_html` folder when checking for new MODx version. I didn't see this behavior prior to Version 2.0.2. No upgrades have been run, it just creates empty folders. 

![screenshot 2018-11-01 09 30 04](https://user-images.githubusercontent.com/1157380/47841251-491b1500-ddb9-11e8-9528-4ab39c7e9a02.png)
![screenshot 2018-11-01 09 30 10](https://user-images.githubusercontent.com/1157380/47841252-491b1500-ddb9-11e8-9f0f-3e81ad576044.png)

**Comment by BobRay** [comment]
That's the expected behavior. Because those directories will be used by more than one processor when you do an upgrade, they're created ahead of time.  Since they're empty, they're taking up almost no disk space.

**Comment by travisbotello** [comment]
Okay, that makes sense. Thanks for clarification!
