### ISSUE TITLE
Cache file downloaded

### ISSUE THREAD

**Issue by FerX** [BobRay/UpgradeMODX#54]
I have many modx sites installed on the same server.
It would be useful for the downloaded file to be saved in /tmp/UpgradeMODX/...
and reused by other sites.

**Comment by BobRay** [comment]
Interesting idea.

You could accomplish this by setting the ugm_temp_dir System Setting to that path, then make these two changes:

Comment out line 50 of the core/components/upgrademodx/processors/cleanup.class.php file:

`// $this->rrmdir($this->tempDir);`

Change line 153 of 

from this:

`if ((!$this->devMode) || (!file_exists($this->tempDir . $this->zipFileName))) {`

to this:

`if (!file_exists($this->tempDir . $this->zipFileName)) {`

**Comment by FerX** [comment]
do you plan to implement it officially in the package?

**Comment by BobRay** [comment]
Thanks for the idea. I haven't had time to test it yet, but the instructions are on the support page at [Bob's guides](https://bobsguides.com/upgrade-modx-package.html) (see the Multiple Installs section).
