### ISSUE TITLE
Could not get version list@

### ISSUE THREAD

**Issue by whitebyte** [BobRay/UpgradeMODX#6]
Sometimes when hitting green button "Upgrade MODx" I recieve this error message inside widget:
`Could not get version list@ /my/path/public_html/core/cache/upgrademodx/versionlist`
I can't clearly reporoduce conditions when it occurs. Manual clearcache + reinstalling Upgrade MODX seems to resolve this, but not always.Any ideas?

MODX 2.3.3 -2.36, Upgrade MODX 1.3.0

**Comment by BobRay** [comment]
I'm not sure, but I think it's a result of UpgradeMODX not getting the data from GitHub. Just logging back in to the Manager (vie the browser's "back" button) and trying again will usually work. I don't think there's any need to re-install.

**Comment by Boddlnagg** [comment]
This happend for me too, and after some investigations I found out that the issue is that `timeToCheck` returned false, but the `upgrademodx` cache directory did not exist (probably because I cleared the cache at some time).

**Comment by BobRay** [comment]
I believe that the latest version is now "cached" in the snippet properties, so clearing the cache shouldn't affect it.  I think the problem may be because the two latest version checks in the snippet are still performed with cURL.

**Comment by Boddlnagg** [comment]
Okay, I don't remember removing that directory manually, but it might still be the case. Anyway, forcing a re-download of the version list if the cached one does not exist should be possible, right?

**Comment by BobRay** [comment]
Good point. There are a number of changes in the new version and this may be fixed. Let me know if it happens again.

**Comment by whitebyte** [comment]
Just ran into this again with UpagradeMODX v .1.3.0

**Comment by BobRay** [comment]
That's odd, the program creates the directory with a permission of 755, Maybe the umask setting is interfering.

You might try commenting out line 52 of the scriptsource chunk:

rmdir($dir);

That may prevent the cache directory from being deleted in the first place. Let me know if that works.

**Comment by whitebyte** [comment]
I believe this is MODX bug, probably this one: https://github.com/modxcms/revolution/issues/9343

**Comment by BobRay** [comment]
That sounds right, but my suggested fix may help with that. I think UGM deletes the cache folder itself (it really shouldn't) and it looks like MODX may be using the wrong permissions when it recreates it.
