### ISSUE TITLE
No dashboard in 2.5.7

### ISSUE THREAD

**Issue by eladnova** [BobRay/UpgradeMODX#65]
Hi Bob
I have a 2.5.7 site which obviously needs an upgrade.
UpgradeMODX will download and install but I see no UI in my dashboard where I believe I should be seeing some kind of upgrade UI.
I have confirmed that the Widget is added to my Dashboard. No evidence of anything when I inspect the Dashboards with the developer tools too.

I note there is a hidden page in the Manager called 'Upgrade MODX' and that I can try to view this. Viewing this in the front end displays an empty page with only partial HTML content down o line 8 which reads
<script type="text/javascript" src="/assets/components/upgrademodx/js/modernizr.custom.js?v=263pl"></script>

If I edit this page in the Manager, I can see some code etc but it's in a rich text field which may be breaking the fucntionality?

**Comment by GitteOlsen** [comment]
I had a similar problem. Also modx 2.5.7. I managed to update MODX manually using ftp, but the problem with Upgrade MODX persists in MODX 2.7.1. No widget showing in the dashboard and the upgrade modx resource also shows a blank page

**Comment by BobRay** [comment]
I've been unable to duplicate this problem.

The display of HTML and JavaScript  on the resource suggests that the content type of the page is something other than HTML. You can check that on the "Settings" tab when editing the resource.

What version of PHP are you both running?

**Comment by GitteOlsen** [comment]
PHP version 5.6.40

The resource is set to "Content type: HTML" and "Content disposition: Inline"

**Comment by BobRay** [comment]
I was finally able to duplicate this. I think 2.5.7 has a problem with widgets. Even with UGM removed, it still doesn't show all its widgets.

I was able to fix it by doing this:

Go to System -> Dashboards. 
Right-click on the Default dashboard and select "Update Dashboard"
Drag the Upgrade MODX widget to the top of the grid so it has a rank of 0
Click on the "Save" button at the upper right.
Click on the MODX logo to see is UGM appears on the dashboard.

**Comment by GitteOlsen** [comment]
Tried it, no luck...

**Comment by BobRay** [comment]
I'm sorry that didn't work for you. Can you try removing the widget from the dashboard, viewing the dashboard, then manually putting the widget back and giving it a rank of 0, then manually deleting all files in the core/cache directory?

**Comment by GitteOlsen** [comment]
Now I see it :-) Not sure what made the difference but it's showing up on my dashboard and viewing the UpdateMODX resource works to. Thanks!

**Comment by BobRay** [comment]
I'm glad it's working for you now.
