### ISSUE TITLE
Error: (modx.com/download) Operation timed out after 5000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by whitebyte** [BobRay/UpgradeMODX#7]
Sometimes when opening manager i see this message instead of UpgradeMODX widget. Unfortunately, I can't see any pattern in when it occurs.

UpgradeMODX 1.3.0
MODX - various 2.3x - 2.4.x

**Comment by whitebyte** [comment]
BTW than you for this extra! This is a real life-saver.

**Comment by BobRay** [comment]
This happens when the MODX site doesn't respond within 5 seconds. Usually, reloading the page will solve it, unless the MODX site is either down or overloaded. There's not really anything UpgradeMODX can do about this.
