### ISSUE TITLE
Empty modx.zip file

### ISSUE THREAD

**Issue by studiorepublic** [BobRay/UpgradeMODX#8]
When I hit upgrade for version 2.4.2 I'm getting a "Unknown error reading /temp directory" error. I've tried debugging the script and it seems that the modx.zip file is being created but it's 0 bytes.

**Comment by BobRay** [comment]
I haven't been able to replicate this. I don't know whether it's a problem with the download from modx.com or with the zip package. Have you tried using the &forcePclZip option?

**Comment by studiorepublic** [comment]
It's a strange one. It's not a zip issue as I can abort the process before it tries to unzip and it's still zero bytes. I'll have another look when I get the chance.

**Comment by BobRay** [comment]
Did you try &forcePclZip? 

What happens if you delete that modx.zip file ahead of time.
