### ISSUE TITLE
UpgradeMODX not always aware of new version

### ISSUE THREAD

**Issue by whitebyte** [BobRay/UpgradeMODX#9]
![bug](https://cloud.githubusercontent.com/assets/7704186/13083846/93fb3da6-d4f8-11e5-9f76-7843fb699efd.png)

Sometimes it shows upgrade button, sometimes doesn't.

**Comment by BobRay** [comment]
The default period for checking is one week. If that property is not changed, UGM will not see a new version until the week is up. Could that be causing your issue?

**Comment by digitalpenguin** [comment]
Me too! It seems 25% of the sites I'm trying to upgrade to 2.5.2 still think 2.5.1 is the latest version.

**Comment by BobRay** [comment]
I've noticed this too, but have been unable to find the cause. It does
straighten out over time for me. I've never seen it lag for more than a
week.

**Comment by digitalpenguin** [comment]
A work-around as brought up by @donshakespeare and @neoneddy on the slack channel is to edit the snippet properties and clear the lastCheck field.

**Comment by BobRay** [comment]
UGM knows there is a new version by looking at the GitHub tags. My guess is that there may be a delay between when the new version is available for download at modx.com and the creation of the tag at GitHub. I believe an API is being created at MODX so UGM won't have to consult GitHub at all. That may solve the problem.
